# Generated by Django 5.0.6 on 2024-05-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('isbn_number', models.DateField(max_length=20)),
                ('page_count', models.IntegerField()),
                ('review_count', models.IntegerField(default=0)),
            ],
        ),
    ]
